# Generated by Django 3.2.3 on 2024-01-10 15:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_tools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, default='studentavar.png', null=True, upload_to='students')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('registration_number', models.CharField(max_length=6, unique=True)),
                ('mobile', models.CharField(blank=True, max_length=11, null=True)),
                ('guardian_mobile', models.CharField(blank=True, max_length=11, null=True)),
                ('ac_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_tools.academicsession')),
                ('student_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_tools.studentclass')),
                ('term', models.ForeignKey(default='1st', on_delete=django.db.models.deletion.CASCADE, to='admin_tools.term')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
