# Generated by Django 3.2.3 on 2024-01-10 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_tools', '0002_studentclass_head'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentclass',
            old_name='head',
            new_name='class_teacher',
        ),
        migrations.RemoveField(
            model_name='studentclass',
            name='code',
        ),
        migrations.RemoveField(
            model_name='studentclass',
            name='establish_date',
        ),
        migrations.AddField(
            model_name='studentclass',
            name='arm',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
