# Generated by Django 3.2.3 on 2024-01-10 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_tools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subject', models.CharField(default='Mathematics', max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('edition', models.CharField(max_length=255)),
                ('year', models.CharField(max_length=10)),
                ('image', models.ImageField(blank=True, upload_to='e_library/images')),
                ('book', models.FileField(blank=True, upload_to='e_library/pdfs')),
                ('book_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_tools.studentclass')),
            ],
        ),
    ]
