# Generated by Django 3.2.3 on 2024-01-10 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0001_initial'),
        ('students', '0001_initial'),
        ('admin_tools', '0002_studentclass_head'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentpaymentinfo',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student'),
        ),
        migrations.AddField(
            model_name='studentpaymentinfo',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_tools.term'),
        ),
        migrations.AddField(
            model_name='schoolfeebalance',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='students.student'),
        ),
    ]
