# Generated by Django 3.2.3 on 2024-01-10 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('admin_tools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonnote',
            name='student_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_tools.studentclass'),
        ),
    ]
